### ISSUE TITLE
OnClicks give blue highlights on touch screens

### ISSUE THREAD

**Issue by riz-l** [riz-l/oneresponse-rework#20]
The below code will remedy this issue when added to the relevant component/class:

`-webkit-tap-highlight-color: transparent;`
- [x] Header: OneResponse Logo
- [x] Header: PatientList toggle
- [x] PatientItem: Whole item
- [x] ReportHeader: Each NavLink

**Comment by tizzle-b-rizzle** [comment]
Hi Riz, I created a pull request but it looks like I can't link it here for some reason, apologies if it's just me missing something.

**Comment by riz-l** [comment]
Error fixed in early October.
