### ISSUE TITLE
Incident Information Responsivness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#27]
Tested at  width 1800px down to 330px (height =1080px throughout):
-1800px: The third column has six items whereas the other two columns have two or four, it is easy to read, but looks odd. The incident number goes all the way across and doesn't go to the next line until 995px.
-<770px: the header's stickiness goes away, I'm guessing this is intentional however.
-680px: There are only two columns now, the first has all items except the last two, which are on the second column
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-468px: Master ePR ID dissapears
-445px: Everything is on one column now
-368: The incident number goes onto two lines.

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
