### ISSUE TITLE
Patient Details Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#28]
Tested at width 1800px down to 330px (height = 1080px throughout)
-861px: For this patient, the GP Surgery name had its last word moved onto the next line, literally no other changes.
-768px: The header loses its stickiness, I believe this is intentional
-700px: GP Address created had one item move onto a new line
-683px: The items are now in two columns, it seems to be like "display: flex" in the all of the first column is filled, however the second column has barely anything on it
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-473px: Everything is on one column now, all the items above the "Patient GP" section look are on the left with a lot of space to the right but that's to be expected

**Comment by riz-l** [comment]
ERR#28: Errors fixed.
