### ISSUE TITLE
Clinical Observations Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#29]
Tested at width 1800px down to 330px (height = 1080px throughout)
*NOTE: The "Total" in "NEWS2 Total" moves all the time whenever an item goes to a new row. If you see "Total goes on 2nd line" or similar it means that the word Total is on a new line, and it goes back to the top whenever an item moves down a row" 
-1800px: All 17 items on one row, the time data spans 2 lines
-1658px: The "(l/min)" in the "Peak flow (l/min)" goes onto the next line
-1602px: The "(mm)" in "Pupil Size (mm)" goes onto the next line
-1442px: The "(sec)" in "Cap Refill (sec)" goes onto the next line
-1296px: The "Total" in "NEWS2 Total" goes onto the next line
-1243px: "Peak Flow (l/min)" moves onto a new row, 
-1222px: The "Total" in "NEWS2 Total" goes onto the next line
-1173px: The "Pain Score" moves onto a new row, 
-1149px: The "Total" in "NEWS2 Total" goes onto the next line
-1103px: The "Pupils React" section goes onto a new row,
-1076px: Total goes on 2nd line
-1033px: "Pupils size (mm)" moves onto the next line, 
-1003px: Total goes on 2nd line
-963px: "BM (M/Mol)" goes onto a new row
-932px: Total goes on 2nd line
-893px: "GCS Total" goes onto a new row
-857px: Total goes on 2nd line
-823px: "GCS" goes onto new row
-784px: Total goes on 2nd line
-768px: Header loses its stickiness
-753px: "Cap Refill (sec)" moves onto new row
-711px: Total goes on 2nd line
-683px: "Peak Flow (l/min)" goes onto a third row
-638px: Total goes on 2nd line
-613px: "Pupils React" moves onto third row
-565px: Total goes on 2nd line 
-543px: "BM (M/Mol)" moves onto a third row
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-492px: Total goes on 2nd line
-472px: "Peak Flow (l/min)" and Pain Score is on a 4th row, the rest make up the other three rows
-462px: The "(sec)" from moves onto a second line "Cap Refil (sec)"
-418px: Total goes on 2nd Line
-403px: The items now span five rows, with "Peak Flow (l/min)" on the fifth row
-380px: The "(sec)" from "Cap Refill (sec)" goes onto a second line
-346px: Total goes on 2nd line
-333px: The items now span six rows, with the last two items on the sixth row

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
