### ISSUE TITLE
IV Access Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#30]
Tested at width 1800px down to 330px (height = 1080px throughout)
-1356px: The "Technique" in "Non-Touch Technique" moves onto a new line
-909px; All of the "Not Recorded" now span two lines
-801px: The data under "Size" now spans two lines
-768px: The header's stickiness dissapears
-750px: Each word of "Non-Touch Technique" has its own line
-635px: The letters from each item are basically right next to each other, much harder to read
-619px: Some letters are now overlapping
-613px: "By" is now on a second row, now no letters are overlapping
-543px: "Attempts" is also now on the second row
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-498px: The Title section of "IV Access and Requirements" now spans two lines, thus the right-hand side is quite empty
-475px: The letters are starting to overlap again
-473px: Non-Touch Technique is now on the second row, the words aren't overlapping now
-403px: The items are now divided equally in two rows of four
-402px: "Non-Touch Technique" is now on three lines instead of two
-340px: Letters getting close enough so that reading is difficult
-335px: Letters now overlap
-333px: The items now span three rows, none of the letters overlap

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
