### ISSUE TITLE
IV Refusal Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#31]
Tested at width 1800px down to 330px (height = 1080px throughout)
-768px: The header's stickiness disappears
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-473px: The items now all span one column, so there is a lot of space on the right

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
