### ISSUE TITLE
Drugs/Meds Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#32]
Tested at width 1800px down to 330px (height = 1080px throughout)
-1315px: Data under "Time" spans two lines
-1248px: Data under "Drug" spans two lines
-1118px: "Own Medications" Now spans two lines
-909px: The "not recorded" now spans two lines
-851px: The data from "Drug" and "Pouch No." are overlapping
-768px: The header's stickiness disappears
-731px: Data from "Route" and "By" overlapping
-713px: Data under "Time" and "Dosage" is overlapping
-613px: "Own Medications is now on a second row", all data on the top row besides "Unit" is overlapping
-543px: "By" is now also on the second row, only the data between "Drug" and "Pouch", and "Time" and "Dosage" is still overlapping
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-473px: "Route" is now on the second row. Data under "Drug" and "Pouch" is overlapping
-403px: All items are now on two rows of four. The data of "Drug" and "Pouch" 
-385px: The data in "Time" and "Dosage" overlaps
-363px: "Pouch No." now spans two lines, and pushes the data down
-333px: The items now span three rows, "Drug" and "Pouch No." data overlaps

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
