### ISSUE TITLE
Drugs Refusal Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#33]
Tested at width 1800px down to 330px (height = 1080px throughout)
-768px: The header's stickiness disappears
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-463px: "Equipment Faulty" under "Type" spans 2 lines now
-378px: "Not recorded" now spans two lines

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
