### ISSUE TITLE
Stroke Assessment Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#35]
Tested at width 1800px down to 330px (height = 1080px throughout)
-1313px: All items under "FAST Assessment" are now 
-768px: The header's stickiness disappears
-683px: The three "groups" now span two rows
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-473px: All groups are now in one column

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
