### ISSUE TITLE
Airways Management Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#36]
Tested at width 1800px down to 330px (height = 1080px throughout)
-768px: The header's stickiness disappears
-716px: The "Airway" in "Nasopharyngeal Airway" has moved onto a second line
-683px: The items are in two columns instead of three
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-495px: The "Airway" in "Nasopharyngeal Airway" has moved onto a second line
-473px: All the items are on one column
-430px: The "Management" in "Airways Management" has moved onto a second line

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
