### ISSUE TITLE
Cardiac Arrest Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#37]
Tested at width 1800px down to 330px (height = 1080px throughout)
-768px: The header's stickiness disappears
-727px: The "Shock" in "Time of First Public AED Shock" moves onto a second line
-683px: The items are now on two columns
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-502px: The "Shock" in "Time of First Public AED Shock" moves onto a second line
-473px: All of the items are on one column

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
