### ISSUE TITLE
Transport Options Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#38]
Tested at width 1800px down to 330px (height = 1080px throughout)
-768px: The header's stickiness disappears
-736px: The "Transported" in "Patient Own Meds Transported" moves onto a second line
-683px: All items are on two columns now
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-508px: The "Transported" in "Patient Own Meds Transported" moves onto a second line
-473px: All items are now in one column
-374px: "Transport Options" now spans two lines

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
