### ISSUE TITLE
Trauma Management Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#39]
Tested at width 1800px down to 330px (height = 1080px throughout)
-768px: The header's stickiness disappears
-683px: The items are now in two columns
-525px: The data under "Area" and "Time" are overlapping
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-473px: The items are now in one column, "By" has moved to a second line
-451px: The data under "Area" and "Time" are overlapping
-418px: The data under "Type" and "Site" are almost touching
-403px: "Time" is now on the second line
-333px: "Area" is now on the second line

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
