### ISSUE TITLE
Communications, Consent, and Notifications Responsiveness Test

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#40]
Tested at width 1800px down to 330px (height = 1080px throughout)
-934px: "Refused Intervention/Treatment" spans two lines
-768px: The header's stickiness disappears
-763px: "Communications, Consent, and Notifications" now spans two lines
-683px: The items span two columns
-518px: When you go to this size, "PATIENT LIST" next to the Patient List toggle, and also the "jjdxc" and "DXC Super User" on the blue bar at the top all vanish
-492px: "Communications, Consent, and Notifications" now spans three lines
-473px: All items are in one column
-344px: Below this width, "Communications, Consent, and Notifications" clips out of its box

**Comment by riz-l** [comment]
Error fixed on 22/10/2020.
