### ISSUE TITLE
DoD Attendance and Relatives Responsiveness Issues

### ISSUE THREAD

**Issue by tizzle-b-rizzle** [riz-l/oneresponse-rework#64]
1568px: The last word of 'Did the patient have a learning disability? If yes, inform support support centre" moves onto the next line, pushing the data down
1362px: The last word of "Bereavement leaflet provided and consider religious support" moves onto the next line, pushing the data down
902px: "Did the patient..." last word moves onto the next line, pushing the data down
728px: "Bereavement..." last word moves onto the next line and the data gets pushed down
695px: Last word of "Details of Police Involvement" goes onto next line, pushes data down

**Comment by riz-l** [comment]
Error fixed.
